---
title: "data preparation"
author: "Frederik Heitmüller"
date: "8 September 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require('XML')) install.packages('XML'); library('XML') 
if (!require('pdftools')) install.packages('pdftools'); library('pdftools') 
if (!require('tabulizer')) install.packages('tabulizer'); library('tabulizer') 
if (!require('rJava')) install.packages('rJava'); library('rJava')
```

# Content

This file contains the major data operation carried out to clean and transform the files used in the SEZ project.

## EU Code of Conduct

Data regarding the work of the EU Code of Conduct Group can be obtained from the website of the European Council under <https://data.consilium.europa.eu/doc/document/ST-9639-2018-REV-4/en/pdf>.


```{r Code of Conduct}

file <- "https://data.consilium.europa.eu/doc/document/ST-9639-2018-REV-4/en/pdf"

out <- extract_tables(file, pages = c(4:95), columns=list(c(5, 10, 20, 30)), method = "stream", encoding="UTF-8", output="matrix")


for (i in c(1:44, 46:90)){
  out[[i]]<- as.data.frame(out[[i]])
  p <- ncol(out[[i]])
   if (p==5){
     colnames(out[[i]])<- c("Country", "Regime", "Standstill", "Assessment", "Rollback")
   }
  if (p==4){
   out[[i]] %<>% add_column(.before=1, Country=NA)
colnames(out[[i]])<- c("Country", "Regime", "Standstill", "Assessment", "Rollback")
}
    if(p==3){
      out[[i]] %<>% add_column(.before=1, Country=NA)
         out[[i]] %<>% add_column(.after=4, Rollback=NA)
         colnames(out[[i]])<- c("Country", "Regime", "Standstill", "Assessment", "Rollback")

    }
     }

for (i in c(45,91)){
    out[[i]]<- as.data.frame(out[[i]])
    out[[i]] %<>% add_column(.after=4, Rollback=NA)
    colnames(out[[i]])<- c("Country", "Regime", "Standstill", "Assessment", "Rollback")

}
 
 df <- as.data.frame(do.call(rbind, out))

 df<- df[-c(1:3, 991:993, 1233:1242),] ##removing former headings from table
df <- as.data.frame(lapply(df, trimws), stringsAsFactors = FALSE) 
num <- which(nchar(df$Standstill)==4, arr.ind=TRUE) ##ttaking all the lines where a standstill date is entered as principal lines
 l <- length(num)  # l tells us how many "principal" lines there are
  l2 <- nrow(df) # l2 tells us how many lines there are in total
  ##now a loop to copy the lines to each other. In the future, try to write this as a function
  for (k in 1:l){
   ## the following feature solves the problem of the last lines at the end
     if (k<l){
      num2 <- num[k+1]-num[k]-1
    }else {
      num2 <- l2-num[k]
    } 
    if(num2>0){ 
     ##here a loop is used to copy one line after the other 
       for (j in 1:num2){
        df[num[k],] <- paste(df[num[k],], df[num[k]+j,], sep=" ")
      }
    } else {}
  }

df2<- df[num,] 
df2 %<>% mutate(eurostat= substr(Regime, start = 1, stop = 2))  
df2 %<>% select(-Country)
df2 %<>% separate(col=Standstill, into=c("StandstillYear", "Institution"), sep=5)  
df2 %<>% separate(col=Regime, into=c("Identifier", "Regime_name"), sep=6)
df2 %<>% separate(col=Regime_name, into=c("rest", "Regime_name"), sep='"')
df2 %<>% select(-rest)
df2 %<>% separate(col=Assessment, into=c("Assessment", "Document"), sep=" \\(doc.")
df2 %<>% mutate(Assessment = str_replace_all(Assessment,"15", ""))
df2 %<>% mutate(Assessment = str_replace_all(Assessment,"HARMFUL", "Harmful"))

df2$Document <- str_replace(df2$Document, "\\)", "")
df2$Document <- str_replace(df2$Document, ". ", "")
df2 %<>% mutate(Rollback= str_replace_all(Rollback,"NA",""))
df2 %<>% mutate(Institution = str_replace_all(Institution,"\\(", ""))
df2 %<>% mutate(Institution = str_replace_all(Institution,"\\)", ""))
df2 %<>% mutate_all(trimws)
df2  %<>% mutate(Institution = na_if(Institution,"")) %<>% mutate(Institution = str_replace_na(Institution, "COCG"))
df2$iso3c <- countrycode(df2$eurostat, origin="eurostat", destination="iso3c")
for (i in 1:nrow(df2)){
if (df2$eurostat[i]=="AN"){df2$iso3c[i] <- "BES"}
  if (df2$eurostat[i]=="NA"){df2$iso3c[i] <- "NAM"}
  }
write_csv2(df2, "codeofconduct.csv")
```