---
title: "under development"
author: "Frederik Heitmüller"
date: "8 September 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Content

This file contains code still under development



```{r circular diagram}
colours <- c("Full exemption or long tax holiday"="#006d2c", 
          "Short tax holiday (10y or less)"="#31a354", 
          "Important reduction (more than 50%)"="#78c679", 
          "Moderate reduction (50% or less)"="#c2e699", 
          "Other tax benefit (gross)"="#ffffcc", 
          "No benefit"="#e41a1c", 
          "Jurisdiction without CIT"="#377eb8",
          "No SEZs"="#984ea3")


colours <- as.data.frame(colours)
colours <- rownames_to_column(colours, var = "category")
complete <- left_join(complete, colours)
complete %<>% mutate_at(.vars="colours", .funs=toupper) ##to write colour names in upper case
complete %<>% mutate(inc_frame_colour = case_when(Membership=="Yes"~"#000000", is.na(Membership)~"#FFFFFF")) ##transforming inclusive framework membership into colours
complete %<>% mutate(SEZ_colour = case_when(SEZno>0~"#000000", SEZno==0~"#FFFFFF")) ### transforming existence of an SEZ into colours                                     
                                       
                                       
circos.par(track.height=0.1, track.margin =c(0.01, 0.06))
circos.initialize(factors=complete$iso3c, xlim = c(0, 10))
## the outer track includes the type of benefit and the country name
circos.track(factors=complete$iso3c, ylim=c(0,10),     panel.fun = function(x, y) {
        circos.text(CELL_META$xcenter, CELL_META$ylim[2]+20, 
                           CELL_META$sector.index, facing="clockwise", cex=0.6)
  circos.rect(xleft=CELL_META$xlim[1], ybottom=CELL_META$ylim[1], xright=CELL_META$xlim[2], ytop=CELL_META$ylim[2], density=-1, col=complete$colours[CELL_META$sector.numeric.index])
})
##this track assesses whether the country is member of the inclusive framework
circos.track(factors=complete$iso3c, ylim=c(0,10),     panel.fun = function(x, y) {
       circos.rect(xleft=CELL_META$xlim[1], ybottom=CELL_META$ylim[1], xright=CELL_META$xlim[2], ytop=CELL_META$ylim[2], density=-1, col=complete$inc_frame_colour[CELL_META$sector.numeric.index])
    })
circos.text(CELL_META$xcenter, CELL_META$ylim[2]+9,"Inclusive Framework Membership", sector.index = "PRY", track.index=2, facing="bending.inside", cex=0.7)        

##this track assesses whether the country has an SEZ
circos.track(factors=complete$iso3c, ylim=c(0,10),     panel.fun = function(x, y) {
       circos.rect(xleft=CELL_META$xlim[1], ybottom=CELL_META$ylim[1], xright=CELL_META$xlim[2], ytop=CELL_META$ylim[2], density=-1, col=complete$SEZ_colour[CELL_META$sector.numeric.index])
    })
circos.text(CELL_META$xcenter, CELL_META$ylim[2]+9,"SEZ exist", sector.index = "PRY", track.index=3, facing="bending.inside", cex=0.7)    

circos.clear()

```
